<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2"><?php echo $heading_title; ?> </h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <h5><?php echo $greating_text; ?> <?php echo $_SESSION['username'];?> </h5>
        </div>
    </div>
</main>