      </div>
    </div>


      <!-- Icons -->
      <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
      <script>
          feather.replace()
      </script>

    <!-- Bootstrap core JavaScript
    ================================================== -->

    <!-- Graphs -->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>-->
   <!-- <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: [1,2,3,4,5,6,7],
          datasets: [{
            data: Array.from({length: 7}, () => Math.floor(Math.random() * 10)-5),
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
      var ctx2 = document.getElementById("myChart2");
      var myChart2 = new Chart(ctx2, {
          type: 'line',
          data: {
              labels: [1,2,3,4,5,6,7],
              datasets: [{
                  data: Array.from({length: 7}, () => Math.floor(Math.random() * 10)-5),
                  lineTension: 0,
                  backgroundColor: 'transparent',
                  borderColor: '#ff0014',
                  borderWidth: 4,
                  pointBackgroundColor: '#ff0014'
              },{
                  data: Array.from({length: 7}, () => Math.floor(Math.random() * 10)-5),
                  lineTension: 0,
                  backgroundColor: 'transparent',
                  borderColor: '#027bff',
                  borderWidth: 4,
                  pointBackgroundColor: '#007bff'
              }]
          },
          options: {
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: false
                      }
                  }]
              },
              legend: {
                  display: false,
              }
          }
      });
    </script>-->
  </body>
</html>