<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title><?php echo $heading_title; ?></title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="view/css/bootstrap.min.css">

    <!-- Custom styles for this template -->
    <link href="view/css/signin.css" rel="stylesheet">

  </head>

  <body class="text-center">
    <form class="form-signin" action="" method="POST" >
      <img class="mb-4" src="view/image/dmovelogo.png" alt="" width="360" height="144">
      <h1 class="h3 mb-3 font-weight-normal"><?php echo $form_title; ?></h1>
      <label for="user" class="sr-only"><?php echo $form_username_text; ?></label>
      <input type="text" name="username" id="user" class="form-control" placeholder="<?php echo $form_username_placeholder; ?>" required autofocus>
      <label for="inputPassword" class="sr-only"><?php echo $form_password_text; ?></label>
      <input type="password" name="password" id="inputPassword" class="form-control" placeholder="<?php echo $form_password_placeholder; ?>" required>
      <button class="btn btn-lg btn-primary btn-block"  name="login" type="submit"><?php echo $button_login; ?></button>
    </form>
  </body>
</html>

