    <div class="container-fluid">
      <div class="row">
        <!--BARRA LATERAL-->
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link" href="<?php echo $side_menu_0_url; ?>">
                  <span data-feather="<?php echo $side_menu_0_icon; ?>"></span>
                  <?php echo $side_menu_0_text; ?>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<?php echo $side_menu_1_url; ?>">
                  <span data-feather="<?php echo $side_menu_1_icon; ?>"></span>
                  <?php echo $side_menu_1_text; ?>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<?php echo $side_menu_2_url; ?>">
                  <span data-feather="<?php echo $side_menu_2_icon; ?>"></span>
                  <?php echo $side_menu_2_text; ?>
                </a>
              </li>
            </ul>
          </div>
        </nav>